# Generated by Django 4.1.1 on 2023-03-05 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(help_text='payment option name', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='payment ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_paid', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('order_key', models.CharField(max_length=200, null=True)),
                ('billing_status', models.BooleanField(default=False)),
                ('payment_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentoption')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='property_payment', to='properties.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.CharField(default='8101815f146d', max_length=12, null=True)),
                ('invoice', models.FileField(null=True, upload_to='invoices/')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payment_invoice', to='payments.payment')),
            ],
        ),
    ]
