"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
import mimetypes
import os, sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fv=b*_p^*voak*7_)ks%fd*udak@u3n89&69ip^rlrirynwei&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #ck editor
    'ckeditor',
    'django_htmx',

    # django filters
    'django_filters',

    # Properties app
    'properties.apps.PropertiesConfig',

    # verifications app
    'verifications',

    #users app
    'users',

    #payments app
    'payments',
    'lodges',

    # bnb
    'bnb',

    # charts
    'chartit',

    # django apscheduler
    'django_apscheduler',

    # user visits
    'django_user_agents',

    # modified tracking analyzer library
    'modified_tracking_analyzer.apps.ModifiedTrackingAnalyzerAppConfig',
]

SITE_ID = 1

ANALYTICAL_INTERNAL_IPS = []

ANALYTICAL_TRACKERS = {
    'google': {
        'tracking_id': 'UA-276480723-1',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',

    # user visit
    'users.custom_middleware.CustomUserVisitMiddleware',

    # user agent
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #custom context managers
                'users.views.contextLoginForm',
                'users.views.contextRegisterForm',
                'properties.views.contextQ',
            ],
            # For custom tag library
            'libraries': {
                'custom_tag': 'bnb.template tags.custom_tags',
                'counter_tag': 'properties.tags.counter'
            }
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES['postgres'] = {
#     'ENGINE': '',
#     'NAME': '',
#     'USER': '',
#     'PASSWORD': '',
#     'HOST': '',
#     'PORT': '',
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

PROJECT_ROOT = os.path.normpath(os.path.dirname(__file__))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = '/media/'

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'templates'),
)

mimetypes.add_type(
    "text/css",
    ".css",
    True,
)

X_FRAME_OPTIONS = 'ALLOWALL'

XS_SHARING_ALLOWED_METHODS = ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']

GEOIP_PATH = os.path.join(PROJECT_ROOT, 'geoip')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

USE_THOUSAND_SEPARATOR = True

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ianlois50@gmail.com'
EMAIL_HOST_PASSWORD = 'utfx fugq lnsu plrz'  # App generated password by google
DEFAULT_FROM_EMAIL = 'ianlois50@gmail.com'

MAP_HIGHLIGHT_COLOR = '#FF0000'
MAP_HIGHLIGHT_OPACITY = 0.5

# configuration for APScheduler
# APSCHEDULER_DATABASE_ALIAS = 'default'

# if 'test' in sys.argv:
#     APSCHEDULER_DATABASE_ALIAS = 'default'

# if 'postgres' in sys.argv:
#     APSCHEDULER_DATABASE_ALIAS = 'postgres'