# Generated by Django 4.1.1 on 2023-03-05 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import properties.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('a_conditioning', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('dining_room', models.BooleanField(default=False, verbose_name='Dining Room')),
                ('laundry', models.BooleanField(default=False, verbose_name='Laundry')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('neighbourhood_w', models.BooleanField(default=False, verbose_name='Neighborhood Watch')),
                ('gym', models.BooleanField(default=False, verbose_name='Gym')),
                ('living_room', models.BooleanField(default=False, verbose_name='Living Room')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50, verbose_name='District Name')),
                ('is_active', models.BooleanField(verbose_name='Active')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.image_upload_path, verbose_name='Property Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Uploaded')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Liked')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Likes',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='NearbyPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_place', models.CharField(max_length=100, verbose_name='Name of Place')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Nearby Place',
                'verbose_name_plural': 'Nearby Places',
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Property Category',
                'verbose_name_plural': 'Property Categories',
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=30, verbose_name='Property Type')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Property Status',
                'verbose_name_plural': 'Property Statuses',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=properties.models.video_upload_path, verbose_name='Property Video')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Uploaded')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Property ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Property')),
                ('price', models.PositiveIntegerField(verbose_name='Property Price')),
                ('location_area', models.CharField(max_length=100, verbose_name='Property Location Area')),
                ('lat', models.CharField(max_length=999, verbose_name='Latitude')),
                ('lon', models.CharField(max_length=999, verbose_name='Longitude')),
                ('views', models.PositiveIntegerField(verbose_name='Number of Views')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('property_type', models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], default='RENT', max_length=7, verbose_name='Property Type')),
                ('year_built', models.DateField(verbose_name='Year Built')),
                ('compound_area', models.PositiveIntegerField(verbose_name='Property Compound Area (metres)')),
                ('no_garages', models.PositiveIntegerField(verbose_name='Number of Garages')),
                ('no_rooms', models.PositiveIntegerField(verbose_name='Number of Rooms')),
                ('no_baths', models.PositiveIntegerField(verbose_name='Number of Baths')),
                ('desc', models.TextField(verbose_name='Description')),
                ('status', models.BooleanField(verbose_name='Property Status')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to=settings.AUTH_USER_MODEL)),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.amenities')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.districts')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.images')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.likes')),
                ('nearby_places', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.nearbyplaces')),
                ('property_cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.propertycategory')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.videos')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
