# Generated by Django 4.1.1 on 2023-04-19 20:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AddField(
            model_name='lodge',
            name='lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lodge',
            name='long',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='country',
            field=models.CharField(default='Malawi', max_length=255),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Duluxe', 'Duluxe'), ('Standard', 'Standard'), ('Economy', 'Economy')], max_length=255),
        ),
    ]
