# Generated by Django 4.1.1 on 2023-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0002_remove_room_number_lodge_lat_lodge_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='adults',
            field=models.PositiveSmallIntegerField(default=2, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='children',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
