# Generated by Django 4.1.1 on 2023-04-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0003_remove_room_capacity_room_adults_room_beds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.amenity')),
                ('lodge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='lodges.lodge')),
            ],
            options={
                'verbose_name': 'Room Amenity',
                'verbose_name_plural': 'Room Amenities',
            },
        ),
        migrations.RemoveField(
            model_name='picture',
            name='room',
        ),
        migrations.AddField(
            model_name='picture',
            name='lodge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='lodges.lodge'),
        ),
        migrations.DeleteModel(
            name='RoomAmenity',
        ),
    ]
