# Generated by Django 4.1.1 on 2023-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0004_lodgeamenity_remove_picture_room_picture_lodge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='lodge_img/'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
