# Generated by Django 4.1.1 on 2023-04-22 17:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0005_lodge_cover_img_lodge_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of your company', max_length=600, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('instagram_link', models.URLField(blank=True, help_text='link to your instagram', null=True)),
                ('twitter_link', models.URLField(blank=True, help_text='link to your twitter', null=True)),
                ('facebook_link', models.URLField(blank=True, help_text='link to your facebook', null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text="link to your what's app", null=True)),
                ('about_text', ckeditor.fields.RichTextField(help_text='what is your company like?', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='your phone number', max_length=10, null=True)),
                ('other_number', models.CharField(blank=True, help_text='other phone number', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, help_text='your email', max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('district', models.CharField(help_text='where are you based?', max_length=300, null=True)),
                ('location', models.CharField(help_text='eg area 18', max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'About  Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=10000, null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('cover_img', models.ImageField(null=True, upload_to='blog_cover_img/')),
                ('author', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Change blog visibility', verbose_name='blog visibility')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='blog_cats', to='lodges.blogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='blog_images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Please add alturnative text', max_length=255, null=True, verbose_name='Alturnative text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='lodges.blogpost')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
